[package]
name = "book_of_shaders"
version = "0.1.0"
edition = "2021"
authors = ["William Pederzoli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
